// Header/login flow with the real test member. usage: node tools/flow.mjs <baseUrl>
import { chromium } from 'playwright';
import { TEST_MEMBER } from './_login-member.mjs';
const base = process.argv[2] || 'http://localhost:5191';
const b = await chromium.launch(); const p = await b.newPage({ viewport: { width: 1280, height: 900 } });
const errs = []; p.on('pageerror', e => errs.push(e.message)); p.on('console', m => m.type() === 'error' && !/status of 400/.test(m.text()) && errs.push(m.text()));
await p.goto(base + '/login', { waitUntil: 'networkidle' });
await p.click('.login-submit-button');
console.log('empty submit error:', await p.textContent('.login-error'));
await p.fill('#login-id', TEST_MEMBER.id); await p.fill('#login-password', 'not-the-password');
await p.click('.login-submit-button'); await p.waitForTimeout(1000);
console.log('wrong password error:', await p.textContent('.login-error'));
await p.fill('#login-password', TEST_MEMBER.password);
await p.click('.login-submit-button'); await p.waitForURL('**/member/dashboard');
console.log('after login url:', p.url());
console.log('member header:', await p.textContent('.header-identity'));
await p.goto(base + '/', { waitUntil: 'networkidle' });
await p.hover('text=Library'); await p.waitForSelector('.nav-menu');
console.log('library menu:', (await p.$$eval('.nav-menu a', a => a.map(x => x.textContent))).join(', '));
await p.screenshot({ path: 'tools/out/menu-library.png', clip: { x: 0, y: 0, width: 1280, height: 220 } });
await p.mouse.move(10, 600);
await p.click('.header-identity'); await p.waitForSelector('.account-menu');
console.log('account menu:', (await p.textContent('.account-menu-head')).replace(/\s+/g, ' '));
await p.screenshot({ path: 'tools/out/menu-account.png', clip: { x: 780, y: 0, width: 500, height: 360 } });
await p.click('.account-menu-logout');
await p.waitForTimeout(500);
console.log('after logout has LOG IN:', await p.isVisible('.header-login'));
await p.fill('.home-input', 'river'); await p.press('.home-input', 'Enter');
console.log('search url:', p.url());
console.log('errors:', errs.length ? errs : 'none');
await b.close();
