import { lazy } from 'react';

// Every page's small-screen rules (generated by tools/responsive.mjs, one file per page root class).
const responsive = import.meta.glob('./styles/responsive/*.css');

/**
 * Code-split a page: its component, its CSS and its small-screen rules are only
 * downloaded when a visitor opens it.
 */
export function lazyPage(load, root) {
  const css = responsive[`./styles/responsive/${root}.css`];
  return lazy(() => Promise.all([load(), css ? css() : null]).then(([mod]) => mod));
}
